// Full league rosters. Logo URLs verified against the ESPN teams API.
// Color rule: if `primary` is black/near-black, `secondary` must be a bright,
// vivid brand color — the UI theme helper falls back to it for contrast.
export const sportsData = {
  nfl: {
    name: "NFL",
    teams: [
      { id: "cardinals_nfl", name: "Arizona Cardinals", short: "ARI", city: "Phoenix", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png", primary: "#97233F", secondary: "#FFB612", text: "#FFFFFF" },
      { id: "falcons", name: "Atlanta Falcons", short: "ATL", city: "Atlanta", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png", primary: "#A71930", secondary: "#A5ACAF", text: "#FFFFFF" },
      { id: "ravens", name: "Baltimore Ravens", short: "BAL", city: "Baltimore", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png", primary: "#241773", secondary: "#9E7C0C", text: "#FFFFFF" },
      { id: "bills", name: "Buffalo Bills", short: "BUF", city: "Buffalo", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png", primary: "#00338D", secondary: "#C60C30", text: "#FFFFFF" },
      { id: "panthers_nfl", name: "Carolina Panthers", short: "CAR", city: "Charlotte", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/car.png", primary: "#0085CA", secondary: "#BFC0BF", text: "#FFFFFF" },
      { id: "bears", name: "Chicago Bears", short: "CHI", city: "Chicago", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png", primary: "#0B162A", secondary: "#C83803", text: "#FFFFFF" },
      { id: "bengals", name: "Cincinnati Bengals", short: "CIN", city: "Cincinnati", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png", primary: "#FB4F14", secondary: "#000000", text: "#FFFFFF" },
      { id: "browns", name: "Cleveland Browns", short: "CLE", city: "Cleveland", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png", primary: "#311D00", secondary: "#FF3C00", text: "#FFFFFF" },
      { id: "cowboys", name: "Dallas Cowboys", short: "DAL", city: "Dallas", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png", primary: "#003594", secondary: "#869397", text: "#FFFFFF" },
      { id: "broncos", name: "Denver Broncos", short: "DEN", city: "Denver", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/den.png", primary: "#FB4F14", secondary: "#002244", text: "#FFFFFF" },
      { id: "lions", name: "Detroit Lions", short: "DET", city: "Detroit", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/det.png", primary: "#0076B6", secondary: "#B0B7BC", text: "#FFFFFF" },
      { id: "packers", name: "Green Bay Packers", short: "GB", city: "Green Bay", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png", primary: "#203731", secondary: "#FFB612", text: "#FFFFFF" },
      { id: "texans", name: "Houston Texans", short: "HOU", city: "Houston", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png", primary: "#03202F", secondary: "#A71930", text: "#FFFFFF" },
      { id: "colts", name: "Indianapolis Colts", short: "IND", city: "Indianapolis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png", primary: "#002C5F", secondary: "#A2AAAD", text: "#FFFFFF" },
      { id: "jaguars", name: "Jacksonville Jaguars", short: "JAX", city: "Jacksonville", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png", primary: "#006778", secondary: "#D7A22A", text: "#FFFFFF" },
      { id: "chiefs", name: "Kansas City Chiefs", short: "KC", city: "Kansas City", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png", primary: "#E31837", secondary: "#FFB81C", text: "#FFFFFF" },
      { id: "raiders", name: "Las Vegas Raiders", short: "LV", city: "Las Vegas", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png", primary: "#000000", secondary: "#A5ACAF", text: "#FFFFFF" },
      { id: "chargers", name: "Los Angeles Chargers", short: "LAC", city: "Los Angeles", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png", primary: "#0080C6", secondary: "#FFC20E", text: "#FFFFFF" },
      { id: "rams", name: "Los Angeles Rams", short: "LAR", city: "Los Angeles", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png", primary: "#003594", secondary: "#FFA300", text: "#FFFFFF" },
      { id: "dolphins", name: "Miami Dolphins", short: "MIA", city: "Miami", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png", primary: "#008E97", secondary: "#FC4C02", text: "#FFFFFF" },
      { id: "vikings", name: "Minnesota Vikings", short: "MIN", city: "Minneapolis", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/min.png", primary: "#4F2683", secondary: "#FFC62F", text: "#FFFFFF" },
      { id: "patriots", name: "New England Patriots", short: "NE", city: "Boston", status: "powerhouse", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png", primary: "#002244", secondary: "#C60C30", text: "#FFFFFF" },
      { id: "saints", name: "New Orleans Saints", short: "NO", city: "New Orleans", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/no.png", primary: "#D3BC8D", secondary: "#101820", text: "#000000" },
      { id: "giants_nfl", name: "New York Giants", short: "NYG", city: "New York", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png", primary: "#0B2265", secondary: "#A71930", text: "#FFFFFF" },
      { id: "jets_nfl", name: "New York Jets", short: "NYJ", city: "New York", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png", primary: "#125740", secondary: "#FFFFFF", text: "#FFFFFF" },
      { id: "eagles", name: "Philadelphia Eagles", short: "PHI", city: "Philadelphia", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png", primary: "#004C54", secondary: "#A5ACAF", text: "#FFFFFF" },
      { id: "steelers", name: "Pittsburgh Steelers", short: "PIT", city: "Pittsburgh", status: "powerhouse", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png", primary: "#000000", secondary: "#FFB612", text: "#FFFFFF" },
      { id: "niners", name: "San Francisco 49ers", short: "SF", city: "San Francisco", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png", primary: "#AA0000", secondary: "#B3995D", text: "#FFFFFF" },
      { id: "seahawks", name: "Seattle Seahawks", short: "SEA", city: "Seattle", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png", primary: "#002244", secondary: "#69BE28", text: "#FFFFFF" },
      { id: "buccaneers", name: "Tampa Bay Buccaneers", short: "TB", city: "Tampa Bay", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png", primary: "#D50A0A", secondary: "#FF7900", text: "#FFFFFF" },
      { id: "titans", name: "Tennessee Titans", short: "TEN", city: "Nashville", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png", primary: "#0C2340", secondary: "#4B92DB", text: "#FFFFFF" },
      { id: "commanders", name: "Washington Commanders", short: "WSH", city: "Washington", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png", primary: "#5A1414", secondary: "#FFB612", text: "#FFFFFF" }
    ]
  },
  nba: {
    name: "NBA",
    teams: [
      { id: "hawks", name: "Atlanta Hawks", short: "ATL", city: "Atlanta", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/atl.png", primary: "#E03A3E", secondary: "#C1D32F", text: "#FFFFFF" },
      { id: "celtics", name: "Boston Celtics", short: "BOS", city: "Boston", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nba/500/bos.png", primary: "#007A33", secondary: "#BA9653", text: "#FFFFFF" },
      { id: "nets", name: "Brooklyn Nets", short: "BKN", city: "New York", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/bkn.png", primary: "#000000", secondary: "#FFFFFF", text: "#FFFFFF" },
      { id: "hornets", name: "Charlotte Hornets", short: "CHA", city: "Charlotte", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/cha.png", primary: "#1D1160", secondary: "#00788C", text: "#FFFFFF" },
      { id: "bulls", name: "Chicago Bulls", short: "CHI", city: "Chicago", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/chi.png", primary: "#CE1141", secondary: "#000000", text: "#FFFFFF" },
      { id: "cavaliers", name: "Cleveland Cavaliers", short: "CLE", city: "Cleveland", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/cle.png", primary: "#860038", secondary: "#FDBB30", text: "#FFFFFF" },
      { id: "mavericks", name: "Dallas Mavericks", short: "DAL", city: "Dallas", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/dal.png", primary: "#00538C", secondary: "#B8C4CA", text: "#FFFFFF" },
      { id: "nuggets", name: "Denver Nuggets", short: "DEN", city: "Denver", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nba/500/den.png", primary: "#0E2240", secondary: "#FEC524", text: "#FFFFFF" },
      { id: "pistons", name: "Detroit Pistons", short: "DET", city: "Detroit", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/det.png", primary: "#C8102E", secondary: "#1D42BA", text: "#FFFFFF" },
      { id: "warriors", name: "Golden State Warriors", short: "GSW", city: "San Francisco", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nba/500/gs.png", primary: "#1D428A", secondary: "#FFC72C", text: "#FFFFFF" },
      { id: "rockets", name: "Houston Rockets", short: "HOU", city: "Houston", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/hou.png", primary: "#CE1141", secondary: "#C4CED4", text: "#FFFFFF" },
      { id: "pacers", name: "Indiana Pacers", short: "IND", city: "Indianapolis", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/ind.png", primary: "#002D62", secondary: "#FDBB30", text: "#FFFFFF" },
      { id: "clippers", name: "LA Clippers", short: "LAC", city: "Los Angeles", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/lac.png", primary: "#C8102E", secondary: "#1D428A", text: "#FFFFFF" },
      { id: "lakers", name: "Los Angeles Lakers", short: "LAL", city: "Los Angeles", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nba/500/lal.png", primary: "#552583", secondary: "#FDB927", text: "#FFFFFF" },
      { id: "grizzlies", name: "Memphis Grizzlies", short: "MEM", city: "Memphis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/mem.png", primary: "#5D76A9", secondary: "#12173F", text: "#FFFFFF" },
      { id: "heat", name: "Miami Heat", short: "MIA", city: "Miami", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/mia.png", primary: "#98002E", secondary: "#F9A01B", text: "#FFFFFF" },
      { id: "bucks", name: "Milwaukee Bucks", short: "MIL", city: "Milwaukee", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/mil.png", primary: "#00471B", secondary: "#EEE1C6", text: "#FFFFFF" },
      { id: "timberwolves", name: "Minnesota Timberwolves", short: "MIN", city: "Minneapolis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/min.png", primary: "#0C2340", secondary: "#78BE20", text: "#FFFFFF" },
      { id: "pelicans", name: "New Orleans Pelicans", short: "NOP", city: "New Orleans", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/no.png", primary: "#0C2340", secondary: "#E31837", text: "#FFFFFF" },
      { id: "knicks", name: "New York Knicks", short: "NYK", city: "New York", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/ny.png", primary: "#006BB6", secondary: "#F58426", text: "#FFFFFF" },
      { id: "thunder", name: "Oklahoma City Thunder", short: "OKC", city: "Oklahoma City", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nba/500/okc.png", primary: "#007AC1", secondary: "#EF3B24", text: "#FFFFFF" },
      { id: "magic", name: "Orlando Magic", short: "ORL", city: "Orlando", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/orl.png", primary: "#0077C0", secondary: "#C4CED4", text: "#FFFFFF" },
      { id: "sixers", name: "Philadelphia 76ers", short: "PHI", city: "Philadelphia", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/phi.png", primary: "#006BB6", secondary: "#ED174C", text: "#FFFFFF" },
      { id: "suns", name: "Phoenix Suns", short: "PHX", city: "Phoenix", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/phx.png", primary: "#1D1160", secondary: "#E56020", text: "#FFFFFF" },
      { id: "blazers", name: "Portland Trail Blazers", short: "POR", city: "Portland", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/por.png", primary: "#E03A3E", secondary: "#000000", text: "#FFFFFF" },
      { id: "kings_nba", name: "Sacramento Kings", short: "SAC", city: "Sacramento", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/sac.png", primary: "#5A2D81", secondary: "#63727A", text: "#FFFFFF" },
      { id: "spurs", name: "San Antonio Spurs", short: "SA", city: "San Antonio", status: "powerhouse", logo: "https://a.espncdn.com/i/teamlogos/nba/500/sa.png", primary: "#000000", secondary: "#C4CED4", text: "#FFFFFF" },
      { id: "raptors", name: "Toronto Raptors", short: "TOR", city: "Toronto", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/tor.png", primary: "#CE1141", secondary: "#A1A1A4", text: "#FFFFFF" },
      { id: "jazz", name: "Utah Jazz", short: "UTA", city: "Salt Lake City", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nba/500/utah.png", primary: "#002B5C", secondary: "#F9A01B", text: "#FFFFFF" },
      { id: "wizards", name: "Washington Wizards", short: "WAS", city: "Washington", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nba/500/wsh.png", primary: "#002B5C", secondary: "#E31837", text: "#FFFFFF" }
    ]
  },
  nhl: {
    name: "NHL",
    teams: [
      { id: "ducks", name: "Anaheim Ducks", short: "ANA", city: "Anaheim", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/ana.png", primary: "#F47A38", secondary: "#B9975B", text: "#FFFFFF" },
      { id: "bruins", name: "Boston Bruins", short: "BOS", city: "Boston", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/bos.png", primary: "#111111", secondary: "#FCB827", text: "#FFFFFF" },
      { id: "sabres", name: "Buffalo Sabres", short: "BUF", city: "Buffalo", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/buf.png", primary: "#003087", secondary: "#FFB81C", text: "#FFFFFF" },
      { id: "flames", name: "Calgary Flames", short: "CGY", city: "Calgary", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/cgy.png", primary: "#D2001C", secondary: "#FAAF19", text: "#FFFFFF" },
      { id: "hurricanes", name: "Carolina Hurricanes", short: "CAR", city: "Raleigh", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/car.png", primary: "#CE1126", secondary: "#A2AAAD", text: "#FFFFFF" },
      { id: "blackhawks", name: "Chicago Blackhawks", short: "CHI", city: "Chicago", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/chi.png", primary: "#CF0A2C", secondary: "#000000", text: "#FFFFFF" },
      { id: "avalanche", name: "Colorado Avalanche", short: "COL", city: "Denver", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/col.png", primary: "#6F263D", secondary: "#236192", text: "#FFFFFF" },
      { id: "bluejackets", name: "Columbus Blue Jackets", short: "CBJ", city: "Columbus", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/cbj.png", primary: "#002654", secondary: "#CE1126", text: "#FFFFFF" },
      { id: "stars", name: "Dallas Stars", short: "DAL", city: "Dallas", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/dal.png", primary: "#006847", secondary: "#8F8F8C", text: "#FFFFFF" },
      { id: "redwings", name: "Detroit Red Wings", short: "DET", city: "Detroit", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/det.png", primary: "#CE1126", secondary: "#FFFFFF", text: "#FFFFFF" },
      { id: "oilers", name: "Edmonton Oilers", short: "EDM", city: "Edmonton", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/edm.png", primary: "#041E42", secondary: "#FF4C00", text: "#FFFFFF" },
      { id: "panthers_nhl", name: "Florida Panthers", short: "FLA", city: "Miami", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/fla.png", primary: "#C8102E", secondary: "#B9975B", text: "#FFFFFF" },
      { id: "kings_nhl", name: "Los Angeles Kings", short: "LA", city: "Los Angeles", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/la.png", primary: "#111111", secondary: "#A2AAAD", text: "#FFFFFF" },
      { id: "wild", name: "Minnesota Wild", short: "MIN", city: "Minneapolis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/min.png", primary: "#154734", secondary: "#A6192E", text: "#FFFFFF" },
      { id: "canadiens", name: "Montreal Canadiens", short: "MTL", city: "Montreal", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/mtl.png", primary: "#AF1E2D", secondary: "#192168", text: "#FFFFFF" },
      { id: "predators", name: "Nashville Predators", short: "NSH", city: "Nashville", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/nsh.png", primary: "#FFB81C", secondary: "#041E42", text: "#000000" },
      { id: "devils", name: "New Jersey Devils", short: "NJ", city: "Newark", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/nj.png", primary: "#CE1126", secondary: "#000000", text: "#FFFFFF" },
      { id: "islanders", name: "New York Islanders", short: "NYI", city: "New York", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/nyi.png", primary: "#00539B", secondary: "#F47D30", text: "#FFFFFF" },
      { id: "rangers", name: "New York Rangers", short: "NYR", city: "New York", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/nyr.png", primary: "#0038A8", secondary: "#CE1126", text: "#FFFFFF" },
      { id: "senators", name: "Ottawa Senators", short: "OTT", city: "Ottawa", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/ott.png", primary: "#DA1A32", secondary: "#B79257", text: "#FFFFFF" },
      { id: "flyers", name: "Philadelphia Flyers", short: "PHI", city: "Philadelphia", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/phi.png", primary: "#F74902", secondary: "#000000", text: "#FFFFFF" },
      { id: "penguins", name: "Pittsburgh Penguins", short: "PIT", city: "Pittsburgh", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/pit.png", primary: "#111111", secondary: "#FCB827", text: "#FFFFFF" },
      { id: "sharks", name: "San Jose Sharks", short: "SJ", city: "San Jose", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/sj.png", primary: "#006D75", secondary: "#EA7200", text: "#FFFFFF" },
      { id: "kraken", name: "Seattle Kraken", short: "SEA", city: "Seattle", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/sea.png", primary: "#001628", secondary: "#99D9D9", text: "#FFFFFF" },
      { id: "blues", name: "St. Louis Blues", short: "STL", city: "St. Louis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/stl.png", primary: "#002F87", secondary: "#FCB514", text: "#FFFFFF" },
      { id: "lightning", name: "Tampa Bay Lightning", short: "TB", city: "Tampa Bay", status: "powerhouse", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/tb.png", primary: "#002868", secondary: "#FFFFFF", text: "#FFFFFF" },
      { id: "leafs", name: "Toronto Maple Leafs", short: "TOR", city: "Toronto", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/tor.png", primary: "#00205B", secondary: "#FFFFFF", text: "#FFFFFF" },
      { id: "mammoth", name: "Utah Mammoth", short: "UTA", city: "Salt Lake City", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/utah.png", primary: "#010101", secondary: "#6CACE4", text: "#FFFFFF" },
      { id: "canucks", name: "Vancouver Canucks", short: "VAN", city: "Vancouver", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/van.png", primary: "#001F5B", secondary: "#008752", text: "#FFFFFF" },
      { id: "knights", name: "Vegas Golden Knights", short: "VGK", city: "Las Vegas", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/vgk.png", primary: "#B4975A", secondary: "#333F48", text: "#FFFFFF" },
      { id: "capitals", name: "Washington Capitals", short: "WSH", city: "Washington", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/wsh.png", primary: "#C8102E", secondary: "#041E42", text: "#FFFFFF" },
      { id: "jets_nhl", name: "Winnipeg Jets", short: "WPG", city: "Winnipeg", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/nhl/500/wpg.png", primary: "#041E42", secondary: "#AC162C", text: "#FFFFFF" }
    ]
  },
  mlb: {
    name: "MLB",
    teams: [
      { id: "diamondbacks", name: "Arizona Diamondbacks", short: "ARI", city: "Phoenix", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/ari.png", primary: "#A71930", secondary: "#E3D4AD", text: "#FFFFFF" },
      { id: "athletics", name: "Athletics", short: "ATH", city: "Las Vegas", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/ath.png", primary: "#003831", secondary: "#EFB21E", text: "#FFFFFF" },
      { id: "braves", name: "Atlanta Braves", short: "ATL", city: "Atlanta", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/atl.png", primary: "#13274F", secondary: "#CE1141", text: "#FFFFFF" },
      { id: "orioles", name: "Baltimore Orioles", short: "BAL", city: "Baltimore", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/bal.png", primary: "#DF4601", secondary: "#000000", text: "#FFFFFF" },
      { id: "redsox", name: "Boston Red Sox", short: "BOS", city: "Boston", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/bos.png", primary: "#BD3039", secondary: "#0C2340", text: "#FFFFFF" },
      { id: "cubs", name: "Chicago Cubs", short: "CHC", city: "Chicago", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/chc.png", primary: "#0E3386", secondary: "#CC3433", text: "#FFFFFF" },
      { id: "whitesox", name: "Chicago White Sox", short: "CHW", city: "Chicago", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/chw.png", primary: "#27251F", secondary: "#C4CED4", text: "#FFFFFF" },
      { id: "reds", name: "Cincinnati Reds", short: "CIN", city: "Cincinnati", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/cin.png", primary: "#C6011F", secondary: "#000000", text: "#FFFFFF" },
      { id: "guardians", name: "Cleveland Guardians", short: "CLE", city: "Cleveland", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/cle.png", primary: "#00385D", secondary: "#E50022", text: "#FFFFFF" },
      { id: "rockies", name: "Colorado Rockies", short: "COL", city: "Denver", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/col.png", primary: "#333366", secondary: "#C4CED4", text: "#FFFFFF" },
      { id: "tigers", name: "Detroit Tigers", short: "DET", city: "Detroit", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/det.png", primary: "#0C2340", secondary: "#FA4616", text: "#FFFFFF" },
      { id: "astros", name: "Houston Astros", short: "HOU", city: "Houston", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/hou.png", primary: "#002D62", secondary: "#EB6E1F", text: "#FFFFFF" },
      { id: "royals", name: "Kansas City Royals", short: "KC", city: "Kansas City", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/kc.png", primary: "#004687", secondary: "#BD9B60", text: "#FFFFFF" },
      { id: "angels", name: "Los Angeles Angels", short: "LAA", city: "Anaheim", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/laa.png", primary: "#BA0021", secondary: "#003263", text: "#FFFFFF" },
      { id: "dodgers", name: "Los Angeles Dodgers", short: "LAD", city: "Los Angeles", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/lad.png", primary: "#005A9C", secondary: "#A5ACAF", text: "#FFFFFF" },
      { id: "marlins", name: "Miami Marlins", short: "MIA", city: "Miami", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/mia.png", primary: "#00A3E0", secondary: "#EF3340", text: "#FFFFFF" },
      { id: "brewers", name: "Milwaukee Brewers", short: "MIL", city: "Milwaukee", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/mil.png", primary: "#12284B", secondary: "#FFC52F", text: "#FFFFFF" },
      { id: "twins", name: "Minnesota Twins", short: "MIN", city: "Minneapolis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/min.png", primary: "#002B5C", secondary: "#D31145", text: "#FFFFFF" },
      { id: "mets", name: "New York Mets", short: "NYM", city: "New York", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/nym.png", primary: "#002D62", secondary: "#FF5910", text: "#FFFFFF" },
      { id: "yankees", name: "New York Yankees", short: "NYY", city: "New York", status: "powerhouse", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/nyy.png", primary: "#0C2340", secondary: "#C4CED4", text: "#FFFFFF" },
      { id: "phillies", name: "Philadelphia Phillies", short: "PHI", city: "Philadelphia", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/phi.png", primary: "#E81828", secondary: "#002D72", text: "#FFFFFF" },
      { id: "pirates", name: "Pittsburgh Pirates", short: "PIT", city: "Pittsburgh", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/pit.png", primary: "#27251F", secondary: "#FDB827", text: "#FFFFFF" },
      { id: "padres", name: "San Diego Padres", short: "SD", city: "San Diego", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/sd.png", primary: "#2F241D", secondary: "#FFC425", text: "#FFFFFF" },
      { id: "giants_mlb", name: "San Francisco Giants", short: "SF", city: "San Francisco", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/sf.png", primary: "#FD5A1E", secondary: "#27251F", text: "#FFFFFF" },
      { id: "mariners", name: "Seattle Mariners", short: "SEA", city: "Seattle", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/sea.png", primary: "#0C2C56", secondary: "#005C5C", text: "#FFFFFF" },
      { id: "cardinals", name: "St. Louis Cardinals", short: "STL", city: "St. Louis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/stl.png", primary: "#C41E3A", secondary: "#0C2340", text: "#FFFFFF" },
      { id: "rays", name: "Tampa Bay Rays", short: "TB", city: "Tampa Bay", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/tb.png", primary: "#092C5C", secondary: "#8FBCE6", text: "#FFFFFF" },
      { id: "rangers_mlb", name: "Texas Rangers", short: "TEX", city: "Dallas", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/tex.png", primary: "#003278", secondary: "#C0111F", text: "#FFFFFF" },
      { id: "bluejays", name: "Toronto Blue Jays", short: "TOR", city: "Toronto", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/tor.png", primary: "#134A8E", secondary: "#6CACE5", text: "#FFFFFF" },
      { id: "nationals", name: "Washington Nationals", short: "WSH", city: "Washington", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/mlb/500/wsh.png", primary: "#AB0003", secondary: "#14225A", text: "#FFFFFF" }
    ]
  },
  mls: {
    name: "MLS",
    teams: [
      { id: "atlanta_utd", name: "Atlanta United FC", short: "ATL", city: "Atlanta", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/18418.png", primary: "#80000A", secondary: "#A29061", text: "#FFFFFF" },
      { id: "austin_fc", name: "Austin FC", short: "ATX", city: "Austin", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/20906.png", primary: "#00B140", secondary: "#000000", text: "#FFFFFF" },
      { id: "montreal_cf", name: "CF Montréal", short: "MTL", city: "Montreal", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9720.png", primary: "#0033A0", secondary: "#C1C5C8", text: "#FFFFFF" },
      { id: "charlotte_fc", name: "Charlotte FC", short: "CLT", city: "Charlotte", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/21300.png", primary: "#1A85C8", secondary: "#000000", text: "#FFFFFF" },
      { id: "chicago_fire", name: "Chicago Fire FC", short: "CHI", city: "Chicago", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/182.png", primary: "#FF0000", secondary: "#141946", text: "#FFFFFF" },
      { id: "rapids", name: "Colorado Rapids", short: "COL", city: "Denver", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/184.png", primary: "#960A2C", secondary: "#9CC2EA", text: "#FFFFFF" },
      { id: "crew", name: "Columbus Crew", short: "CLB", city: "Columbus", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/183.png", primary: "#FED102", secondary: "#000000", text: "#000000" },
      { id: "dc_united", name: "D.C. United", short: "DC", city: "Washington", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/193.png", primary: "#231F20", secondary: "#EF3E42", text: "#FFFFFF" },
      { id: "cincinnati", name: "FC Cincinnati", short: "CIN", city: "Cincinnati", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/18267.png", primary: "#F05323", secondary: "#263B80", text: "#FFFFFF" },
      { id: "fc_dallas", name: "FC Dallas", short: "DAL", city: "Dallas", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/185.png", primary: "#E81F3E", secondary: "#2A4076", text: "#FFFFFF" },
      { id: "dynamo", name: "Houston Dynamo FC", short: "HOU", city: "Houston", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/6077.png", primary: "#FF6B00", secondary: "#101820", text: "#FFFFFF" },
      { id: "miami", name: "Inter Miami CF", short: "MIA", city: "Miami", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/20232.png", primary: "#F7B5CD", secondary: "#231F20", text: "#000000" },
      { id: "galaxy", name: "LA Galaxy", short: "LA", city: "Los Angeles", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/187.png", primary: "#00245C", secondary: "#FFD200", text: "#FFFFFF" },
      { id: "lafc", name: "Los Angeles FC", short: "LAFC", city: "Los Angeles", status: "champs", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/18966.png", primary: "#000000", secondary: "#C39C5E", text: "#FFFFFF" },
      { id: "minnesota_utd", name: "Minnesota United FC", short: "MIN", city: "Minneapolis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/17362.png", primary: "#000000", secondary: "#8CD2F4", text: "#FFFFFF" },
      { id: "nashville_sc", name: "Nashville SC", short: "NSH", city: "Nashville", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/18986.png", primary: "#ECE83A", secondary: "#1F1646", text: "#000000" },
      { id: "revolution", name: "New England Revolution", short: "NE", city: "Boston", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/189.png", primary: "#0A2240", secondary: "#CE0E2D", text: "#FFFFFF" },
      { id: "nycfc", name: "New York City FC", short: "NYC", city: "New York", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/17606.png", primary: "#6CACE4", secondary: "#041E42", text: "#000000" },
      { id: "rbny", name: "New York Red Bulls", short: "RBNY", city: "New York", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/190.png", primary: "#ED1E36", secondary: "#23326A", text: "#FFFFFF" },
      { id: "orlando_city", name: "Orlando City SC", short: "ORL", city: "Orlando", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/12011.png", primary: "#633492", secondary: "#FDE192", text: "#FFFFFF" },
      { id: "union", name: "Philadelphia Union", short: "PHI", city: "Philadelphia", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/10739.png", primary: "#071B2C", secondary: "#B49759", text: "#FFFFFF" },
      { id: "timbers", name: "Portland Timbers", short: "POR", city: "Portland", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9723.png", primary: "#004812", secondary: "#EAE228", text: "#FFFFFF" },
      { id: "rsl", name: "Real Salt Lake", short: "RSL", city: "Salt Lake City", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/4771.png", primary: "#B30838", secondary: "#F2A900", text: "#FFFFFF" },
      { id: "san_diego_fc", name: "San Diego FC", short: "SD", city: "San Diego", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/22529.png", primary: "#697A7C", secondary: "#F89E1A", text: "#FFFFFF" },
      { id: "earthquakes", name: "San Jose Earthquakes", short: "SJ", city: "San Jose", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/191.png", primary: "#0051BA", secondary: "#000000", text: "#FFFFFF" },
      { id: "sounders", name: "Seattle Sounders FC", short: "SEA", city: "Seattle", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9726.png", primary: "#005C5C", secondary: "#85B623", text: "#FFFFFF" },
      { id: "sporting_kc", name: "Sporting Kansas City", short: "SKC", city: "Kansas City", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/186.png", primary: "#002F65", secondary: "#91B0D5", text: "#FFFFFF" },
      { id: "stl_city", name: "St. Louis CITY SC", short: "STL", city: "St. Louis", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/21812.png", primary: "#EC1458", secondary: "#041C2C", text: "#FFFFFF" },
      { id: "toronto_fc", name: "Toronto FC", short: "TOR", city: "Toronto", status: "heartbreak", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/7318.png", primary: "#E31937", secondary: "#A3A7AC", text: "#FFFFFF" },
      { id: "whitecaps", name: "Vancouver Whitecaps FC", short: "VAN", city: "Vancouver", status: "standard", logo: "https://a.espncdn.com/i/teamlogos/soccer/500/9727.png", primary: "#04265C", secondary: "#9DC2EA", text: "#FFFFFF" }
    ]
  }
};
